---
name: CI

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - '**.md'
      - 'LICENSE*'
      - '.gitignore'
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - '**.md'
      - 'LICENSE*'
      - '.gitignore'

jobs:
  ci:
    uses: riccione/github-workflows/.github/workflows/rust-ci.yml@a42157e21f91d87ff97e4a6a30f431f687052064
