---
name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    uses: riccione/github-workflows/.github/workflows/rust-release.yml@1192f46ded92a871dd9f4b8c7166ef8f09774a9b
    permissions:
      contents: write
    with:
      bin_name: hermes-otp
      tag: ${{ github.ref_name }}
