---
name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    uses: riccione/github-workflows/.github/workflows/rust-release.yml@309464f75695501b26e988010273cc182de38f3a
    permissions:
      contents: write
    with:
      bin_name: hermes-otp
      tag: ${{ github.ref_name }}
