---
name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    uses: riccione/github-workflows/.github/workflows/rust-release.yml@fa495febd747cdcf8edcba3bf0315115d6add639
    permissions:
      contents: write
    with:
      bin_name: hermes-otp
      tag: ${{ github.ref_name }}
